/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [projectOffice]    Script Date: 02/01/2018 08:55:16 ******/
CREATE DATABASE [projectOffice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projectOffice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\projectOffice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projectOffice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\projectOffice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [projectOffice] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projectOffice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projectOffice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projectOffice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projectOffice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projectOffice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projectOffice] SET ARITHABORT OFF 
GO

ALTER DATABASE [projectOffice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projectOffice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projectOffice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projectOffice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projectOffice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projectOffice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projectOffice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projectOffice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projectOffice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projectOffice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projectOffice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projectOffice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projectOffice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projectOffice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projectOffice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projectOffice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projectOffice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projectOffice] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [projectOffice] SET  MULTI_USER 
GO

ALTER DATABASE [projectOffice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projectOffice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projectOffice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projectOffice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projectOffice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projectOffice] SET QUERY_STORE = OFF
GO

USE [projectOffice]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [projectOffice] SET  READ_WRITE 
GO

